# Etapa 1: Construcción
FROM node:18-alpine AS build

# Establecer directorio de trabajo en el contenedor
WORKDIR /app

# Copiar package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instalar las dependencias necesarias
RUN npm install --production

# Copiar el resto del código fuente de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine

# Copiar los archivos estáticos de la construcción al directorio que Nginx sirve por defecto
COPY --from=build /app/build /usr/share/nginx/html

# Copiar el archivo de configuración de Nginx (opcional)
# Si necesitas un archivo de configuración personalizado de Nginx, descomenta la siguiente línea
# COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto en el que Nginx estará sirviendo la aplicación
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
